name: semesta
description: "A Social Media App in Flutter"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ^3.9.2

# versions available, run `flutter pub outdated`.
dependencies:
    flutter:
        sdk: flutter

    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.8
    firebase_core: ^4.2.0
    get: ^4.7.2
    go_router: ^16.3.0
    firebase_auth: ^6.1.1
    cloud_firestore: ^6.0.3
    firebase_storage: ^13.0.3
    firebase_messaging: ^16.0.3
    firebase_analytics: ^12.0.3
    cached_network_image: ^3.4.1
    shimmer: ^3.0.0
    intl: ^0.20.2
    flutter_staggered_grid_view: ^0.7.0
    connectivity_plus: ^7.0.0
    photo_view: ^0.15.0
    video_player: ^2.10.0
    flutter_native_splash: ^2.4.7
    logger: ^2.6.2
    file_picker: ^10.3.3
    google_sign_in: ^7.2.0
    flutter_screenutil: ^5.9.3
    firebase_crashlytics: ^5.0.3
    onesignal_flutter: ^5.3.4
    shared_preferences: ^2.5.3
    provider: ^6.1.5+1
    flutter_facebook_auth: ^7.1.2
    hashids2: ^2.0.0
    form_builder_validators: ^11.2.0
    flutter_form_builder: ^10.2.0
    firebase_app_check: ^0.4.1+2
    jiffy: ^6.4.3
    equatable: ^2.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter

    # rules and activating additional ones.
    flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter:
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/icons/

    # "family" key with the font family name, and a "fonts" key with a
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
